### ISSUE TITLE
Infographics for Blog

### ISSUE THREAD

**Issue by Levityss** [skycoin/blog#596]
I think we should release these one a day on the blog in coordination with social media as well. Post on blog then post blog page on social media. 

I made these @ 1000 width. There are higher rez on syncthing. Not sure if we want to go smaller than 1000. 

[7 Infographix.zip](https://github.com/skycoin/blog/files/1650442/7.Infographix.zip)

**Comment by gz-c** [comment]
We need a series of pull requests, each adding the new image to an images folder and a .md file linking to the image
