### ISSUE TITLE
Add opengraph meta tags to the header

### ISSUE THREAD

**Issue by gz-c** [skycoin/blog#627]
Extending upon #613 

Opengraph protocol:
http://ogp.me/

Add the following to the header:

* og:title
* og:url
* og:locale
* og:locale:alternate
* og:site_name
* og:type (article for blog posts, website for the other pages)
* og:type article tags (published_time, section, tags)

Separate PRs can be submitted for each of these tags. Some may be difficult to do (such as og:locale:alternate)

**Comment by olemis** [comment]
Cc @stdevHan
