### ISSUE TITLE
Remove outdated statement: $40 transaction... (Skycoin Digest: What do you think of Bitcoin? [INFOGRAPHIC])

### ISSUE THREAD

**Issue by escapedcat** [skycoin/blog#676]
https://www.skycoin.net/blog/infographics/what-do-you-think-about-bitcoin/
> $40 transaction fees and climbing!

Ths infographic is outdated.  
It's not a valid statement (anymore). For example see: https://bitcoinfees.info
Since Segwit and Lightning are picking gaining tracktion fees are getting low (again).

**Comment by gz-c** [comment]
stop wasting our time
