### ISSUE TITLE
Add image caption CSS/formatting

### ISSUE THREAD

**Issue by gz-c** [skycoin/blog#847]
There is no way to do image caption text in a nice way, like Medium has

**Comment by gz-c** [comment]
Seems we can use the `figure` shortcode along with some css, e.g. https://github.com/gcushen/hugo-academic/issues/655

**Comment by gz-c** [comment]
We can use <figure> but needs CSS to look good

**Comment by haroonskycoin** [comment]
I updated the CSS for the blog.  Mark this resolved please.

**Comment by gz-c** [comment]
For future reference you can write "fixes #xxx" in the PR description or in your commit message and it will automatically close the issue once merged
