### ISSUE TITLE
Fix spacing below list

### ISSUE THREAD

**Issue by jdknives** [skycoin/blog#856]
Refer to this post to check the spacing after unordered list (not tested for ordered lists): https://www.skycoin.net/blog/posts/skywire-mainnet-development-update/

The spacing needs to be smaller.

**Comment by gz-c** [comment]
The CSS for `ul` and `li` is insufficient. There are a number of issues with margins/padding around lists. Part of the problem is because the blog post itself is inside of a list, so the CSS is applied in different contexts, due to a simple `ul li` selector
