### ISSUE TITLE
Add the list of links to the end of every post automatically

### ISSUE THREAD

**Issue by gz-c** [skycoin/blog#876]
Add the list of links to the end of every post automatically.

The list is:

Skycoin Store: https://store.skycoin.net/
Website: https://www.skycoin.net/
Telegram: https://t.me/Skycoin
Twitter: https://twitter.com/Skycoinproject
Reddit: https://reddit.com/r/Skycoin
YouTube: https://www.youtube.com/c/skycoin
Facebook: https://www.facebook.com/groups/skycoinofficial
LinkedIn: https://www.linkedin.com/company/skycoin

**Comment by gz-c** [comment]
After this is done, blog posts that have the links added manually should be edited, so that they don't print them twice

**Comment by berli96** [comment]
@gz-c fixed it #879

**Comment by haroonskycoin** [comment]
> After this is done, blog posts that have the links added manually should be edited, so that they don't print them twice

Vidya has completed this
